### ISSUE TITLE
Review Feedback

### ISSUE THREAD

**Issue by akashdhandeib** [ananyalathi19/to-do-list#1]
Hi @ananyalathi19,

I will list my observations and suggestions here.

- [ ] Separate styles in .css file.
- [ ] Create architecture (``index.html, assets/css, assets/js, assets/images`` folders)
- [ ] Check console, no errors should be present.
- [ ] Host it on firebase for testing.
- [ ] Improve the UI, make it like an app you would like to use.
- [ ] Have some default TODO items in the list.
- [ ] Remove console from code, use console only in development time. make sure no errors in console.
- [ ] Add validation, ie. user should not enter blank todo, confirmation on delete todo.
- [ ] Try to refactor code with jQuery, add Javascript in a separate file.

Let me know if you have any questions/queries.

Thanks

**Comment by akashdhandeib** [comment]
#Create progress plan

##Phase 1

##Phase 2



##Final Product

**Comment by akashdhandeib** [comment]
You can refer to https://keep.google.com

**Comment by akashdhandeib** [comment]
![image](https://user-images.githubusercontent.com/26922593/109927837-cb4dd800-7cea-11eb-8b16-7e0b47de03f7.png)

**Comment by akashdhandeib** [comment]
**File Naming:** 
No space in filename
No special character in filename
No capitalization in filename
